### ISSUE TITLE
What is FOSS license?

### ISSUE THREAD

**Issue by shakna-israel** [httpsGithubParty/FOSS-for-Dev#1]

**Comment by tvvocold** [comment]
See https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
And here is an easy way to find out:
`It's in github and  got a free License (both FSF-approved & OSI-approved are OK i think:)`

**Comment by tvvocold** [comment]
Need an Expert on this subject, hi there @sztsian :  Anyidea?

**Comment by tvvocold** [comment]
Just find a book about FOSS licensing might be helpful:
http://www.math.unipd.it/~bellio/Free%20Open%20Source%20Software%20-%20Licensing.pdf

**Comment by shakna-israel** [comment]
Sorry, I was not asking what a license is.

I was asking what license covers this repository. In the README, there is this line:

```
Feel free to send a PR , please check the License First :)
```

But I do not see a license to look at.

**Comment by tvvocold** [comment]
https://github.com/httpsGithubParty/FOSS-for-Dev/blob/master/LICENSE
:)

**Comment by shakna-israel** [comment]
Thanks

**Comment by sztsian** [comment]
@tvvocold  I am really not an expert in license. 

But I want to raise one question. What is this project aims at? MIT is a license for program/software better than contents. So if you are aiming at gathering information, and the license is for the project(content) instead of the program listed, you should consider choose a CC license

**Comment by tvvocold** [comment]
No Offense, but i like this [license](https://github.com/httpsGithubParty/FOSS-for-Dev/blob/master/LICENSE) :)
